ARG BASE_IMAGE=nvcr.io/nvidia/deepstream:6.1-devel
FROM ${BASE_IMAGE}


WORKDIR /home
RUN git clone https://github.com/marcoslucianops/DeepStream-Yolo \
    && cd DeepStream-Yolo \
    && CUDA_VER=11.6 make -C nvdsinfer_custom_impl_Yolo

WORKDIR /home/model/
CMD ["deepstream-app", "-c", "config_yolov4-p6.txt"]